from configs.ToRURAL import SOURCE_DATA_CONFIG,TARGET_DATA_CONFIG, EVAL_DATA_CONFIG, TARGET_SET
IGNORE_LABEL = -1
MOMENTUM = 0.9
NUM_CLASSES = 7

SNAPSHOT_DIR = '/home/qq/code/liujiawei/SwinTransformer/dalog/ce/'
#Hyper Paramters
WEIGHT_DECAY = 0.0005
LEARNING_RATE = 1e-4
NUM_STEPS = 50000
PREHEAT_STEPS = int(NUM_STEPS / 20)
POWER = 0.9
EVAL_EVERY=4000
TRAIN_EVERY=9000
WARMUP_STEP=1500

TARGET_SET = TARGET_SET
SOURCE_DATA_CONFIG=SOURCE_DATA_CONFIG
TARGET_DATA_CONFIG=TARGET_DATA_CONFIG
EVAL_DATA_CONFIG=EVAL_DATA_CONFIG

# ad
TRAIN_LAMBDA_ADV_MAIN=0.0002
TRAIN_LAMBDA_ADV_AUX =0.001