from configs.DAToRURAL import SOURCE_DATA_CONFIG,TARGET_DATA_CONFIG, EVAL_DATA_CONFIG, TARGET_SET
IGNORE_LABEL = -1
MOMENTUM = 0.9
NUM_CLASSES = 7

SNAPSHOT_DIR = '/home/qq/code/liujiawei/SwinTransformer/dalog/focal/'

#Hyper Paramters
WEIGHT_DECAY = 0.0005
LEARNING_RATE = 1e-4
NUM_STEPS = 50000
NUM_STEPS_STOP=50000
PREHEAT_STEPS = int(NUM_STEPS / 20)
POWER = 0.9
EVAL_EVERY=4000
TRAIN_EVERY=9000
WARMUP_STEP=1500
LEARNING_RATE_D = 1e-5
NUM_STEPS = 50000
ITER_SIZE=1
LAMBDA_SEG = 0.1
LAMBDA_ADV_TARGET1 = 0.0002
LAMBDA_ADV_TARGET2 = 0.001


TARGET_SET = TARGET_SET
SOURCE_DATA_CONFIG=SOURCE_DATA_CONFIG
TARGET_DATA_CONFIG=TARGET_DATA_CONFIG
EVAL_DATA_CONFIG=EVAL_DATA_CONFIG

# ad
TRAIN_LAMBDA_ADV_MAIN=2
TRAIN_LAMBDA_ADV_AUX =1
